version: 2
services:
  - type: web
    name: heavy-render-website
    env: static
    staticPublishPath: ./
    buildCommand: echo "Static site ready"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
